### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: THUDM/chatglm3-6b
adapter_name_or_path: saves/chatglm3-6b/lora/sft
template: chatglm3
finetuning_type: lora
trust_remote_code: true

### export
export_dir: models/chatglm3_lora_sft
export_size: 2
export_device: cpu
export_legacy_format: false
# export_hub_model_id: "klaylouis1932/chatglm3-6b-lora-ft-fin"